apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-armv6
  labels:
    app: postgres-armv6
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin123
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-armv6
  labels:
    type: local
    app: postgres-armv6
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-armv6
  labels:
    app: postgres-armv6
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-armv6
  labels:
    app: postgres-armv6
spec:
  type: LoadBalancer
  ports:
   - port: 5432
  selector:
   app: postgres-armv6
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-armv6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-armv6
      version: v1
  template:
    metadata:
      labels:
        app: postgres-armv6
        version: v1
    spec:
      containers:
        - name: postgres-armv6
          image: postgres@sha256:1cce97cb48841d62e73ef1c14dccf3b8aa15b08d3689d6dac2982d30e6e3fdf5
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config-armv6
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb-armv6
      volumes:
        - name: postgredb-armv6
          persistentVolumeClaim:
            claimName: postgres-pv-claim-armv6
---